# -  /CodeRick/

FROM quay.io/suhailtechinfo/suhail-v2
RUN git clone https://github.com/CodeRick-23/CodeRick-MD /root/CodeRick
WORKDIR /root/CodeRick/
RUN npm install
EXPOSE 8000
CMD ["npm","start","yarn" ]
  
# -  /CodeRick/ Don't change this name,
